version: "3.9"

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    #image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/package-lock.json:/opt/package-lock.json
      - ./backend/.env:/opt/app/.env
    ports:
      - '1337:1337'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx-proxy:
    image: nginx
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'
    restart: unless-stopped